
export const FETCH_ARTICLE_LIST = 'FETCH_ARTICLE_LIST'
export const SET_ARTICLE_LIST = 'SET_ARTICLE_LIST'
export const VIEW_ARTICLE_MORE = 'VIEW_ARTICLE_MORE'


export const BEGIN_LOAD = "BEGIN_LOAD"
export const LOAD_SUCCES = "LOAD_SUCCES"
export const LOAD_ERROR = "LOAD_ERROR"