

export const FETCH_ARTICLE = 'FETCH_ARTICLE'
export const SET_ARTICLE = 'SET_ARTICLE'

export const SET_COMMENT = 'SET_COMMENT'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const FETCH_SUCCESS = 'FETCH_SUCCESS'
export const FETCH_ERROR = 'FETCH_ERROR'

export const FETCH_COMMENT = 'FETCH_COMMENT'
export const SET_COMMENTLIST = 'SET_COMMENTLIST'
