
export const FETCH_ARTICLE_RECENT = 'FETCH_ARTICLE_RECENT'
export const SET_ARTICLE_RECENT = 'SET_ARTICLE_RECENT'
export const FETCH_ARTICLE_HOT = 'FETCH_ARTICLE_HOT'
export const SET_ARTICLE_HOT = 'SET_ARTICLE_HOT'
export const FETCH_TAG_LIST = 'FETCH_TAG_LIST'
export const SET_TAG_LIST = 'SET_TAG_LIST'


export const BEGIN_LOAD = "BEGIN_LOAD"
export const LOAD_SUCCES = "LOAD_SUCCES"
export const LOAD_ERROR = "LOAD_ERROR"